// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    authDomain: '***REMOVED***.firebaseapp.com',
    storageBucket: '***REMOVED***.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:android:41ced3639f94e9abcbf8b4',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:ios:29abef0470a9e5e4cbf8b4',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
    iosBundleId: 'com.example.marketinya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:ios:29abef0470a9e5e4cbf8b4',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
    iosBundleId: 'com.example.marketinya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:web:10d1a63827ac16cacbf8b4',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    authDomain: '***REMOVED***.firebaseapp.com',
    storageBucket: '***REMOVED***.appspot.com',
  );
}
