// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

enum FirebaseEnvironment { wip, prod }

class DefaultFirebaseOptions {
  static FirebaseEnvironment _environment = FirebaseEnvironment.wip;

  static void setEnvironment(FirebaseEnvironment environment) {
    _environment = environment;
  }

  static FirebaseEnvironment get currentEnvironment => _environment;

  static FirebaseOptions get currentPlatform {
    switch (_environment) {
      case FirebaseEnvironment.wip:
        return _getWipOptions();
      case FirebaseEnvironment.prod:
        return _getProdOptions();
    }
  }

  static FirebaseOptions _getWipOptions() {
    if (kIsWeb) {
      return wipWeb;
    }
    throw UnsupportedError(
      'WIP environment only supports web platform. '
      'Use PROD environment for mobile platforms or add WIP mobile configuration.',
    );
  }

  static FirebaseOptions _getProdOptions() {
    if (kIsWeb) {
      return prodWeb;
    }
    throw UnsupportedError(
      'PROD environment only supports web platform. '
      'Android, iOS, macOS, and Windows apps have been deleted from Firebase.',
    );
  }

  static const FirebaseOptions wipWeb = FirebaseOptions(
    apiKey: 'AIzaSyCPbj5wmHpfzRCYofkrA-C_3xq8dpHhki0',
    appId: '1:234284642167:web:6add026728671005d83b72',
    messagingSenderId: '234284642167',
    projectId: 'marketiniya-wip',
    authDomain: 'marketiniya-wip.firebaseapp.com',
    storageBucket: 'marketiniya-wip.firebasestorage.app',
    measurementId: 'G-VNFXXGWGE0',
  );

  static const FirebaseOptions prodWeb = FirebaseOptions(
    apiKey: 'AIzaSyCGk6jQHDk0RRXoE3wcwlz6N8ckVAZ_1WM',
    appId: '1:1083783475549:web:a56c6759983cb1ebcbf8b4',
    messagingSenderId: '1083783475549',
    projectId: 'marketinya-a4876',
    authDomain: 'marketinya-a4876.firebaseapp.com',
    storageBucket: 'marketinya-a4876.appspot.com',
  );
}
