name: Semgrep

on:
  pull_request:
    branches: [ "master" ]

jobs:
  semgrep:
    name: Semgrep-Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    container:
      image: semgrep/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Supply Chain Scan
        run: semgrep ci --supply-chain
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Run Semgrep Code Scan
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            semgrep ci --code
          else
            semgrep ci --code || true
          fi
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
